version: 1 
runtime: python27
api_version: 1 
threadsafe: true

handlers:
- url: /bootstrap
  static_dir: bootstrap

#- url: /task
#  script: main.app
#  login: admin

- url: /.*
  script: main.app
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

